# Paths in this file can either be absolute or relative to this repositories location on your machine

# The root of your gclient configured directory, this is the directory containing the "src" folder
electronRoot: /Users/me/projects/electron-gn

# The path to a directory to use as your chromium git cache, this directory must exist
gitCachePath: .git-cache

# (Optional): The name of the "out/X" directory to use, default is "Debug"
# electronOutDir: Debug